---
title: "Enrollments"
author: "Tanya Rohatgi"
date: "9/26/2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(knitr)
```

```{r, warning=FALSE}
x <- read_rds("enrollment.rds")
x %>%
  select(course_name, u_grad)
x

x %>%
  select(course_name, course_title, course_department, u_grad) %>%
  arrange(desc(u_grad))

x %>%
  filter(!is.na(course_name)) %>% #Because there are over 20000 NAs
  select(course_name, course_title, course_department, u_grad) %>%
  arrange(desc(u_grad)) %>%
  head(n = 10) %>% # Top 10 courses
  kable(caption = "Enrollment Data") # went back and added knitr library so we have the function kable, basically to get a better looking table when knit

#Put echo=FALSE to hide code in knit. Break up chunks if needed to hide only what you want to hide.
```
```{r}
x %>%
  mutate(c_length = nchar(course_name)) %>%
  select(c_length, course_name) %>%
  arrange(c_length) %>%
  head(n = 7) #Can also use slice(1:7)
```


